# Site settings
title: Financing malaria control in Mozambique
header-img: img/landing.JPG
email: joe@gmail.com
description: "Private-sector foreign financing of malaria control and eradication: investigating preferences and quantifying its benefits and costs"
url: "joebrew.github.io"
twitter_username: bcndata
github_username:  joebrew
facebook_username:  joebrew

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
