---
output:
  html_document:
    theme: united
    highlight: tango
---

```{r setup, include=FALSE}
library(knitr)
library(dplyr)
# Basic knitr options
opts_chunk$set(comment = NA, 
               echo = FALSE, 
               warning = FALSE, 
               message = FALSE, 
               error = TRUE, 
               cache = F,
               fig.width = 4,
               fig.height = 3)
knit_engines$set(asis = function(options) {
  if (options$echo && options$eval) knit_child(text = options$code)
})
```

# Meeting: 2018-04-16

_Maragra paper_

1. Intro / main argument. One of the following two (but which one):
- "how does malaria affect workers" vs. 
- "what is ROI on malaria control". 

2. Methods / models. Fixed effects, random effects, "mixed effects". As of now, we're doing:
- fixed effects for individual workers
- random effects for other variables
- 4 different models for the 4 different worker types

Elisa asked:
- "linear mixed effect model is used because there is likely to be no independence across time points?"


3. Results and number of models: I'd like your opinion on the use of the 4 segregated models to account for potentially different time-varying effects of IRS on absenteeism.


4. Results and how to deal with sickness: I'd like your opinion on the extent to which I should go in to depth regarding the data we have on clinical malaria. On the one hand, we have so much (lab tests, worker identity, parasite severity etc.). On the other hand, it doesn't seem to track with the epi of malaria and probably is only a small (and biased) sub-sample of all malaria.

5. Journal: As of now, the target is "Journal of Health Economics." I'd like your opinion regarding whether this is an appropriate target or not (so that I can "re-target" if not).


6. Missed opportunities? Is this paper (in its current version) missing any "big picture" issues?

7. Interpreting results / table 3. Menno said "These effects are opposite what you would expect. In the graph it seemed that in the off malaria season there was just no effect. Are these estimates the same as what is reported in the graph?" We need to discuss interpreting interactions, etc.

